### ISSUE TITLE
Question about salt

### ISSUE THREAD

**Issue by jo-wil** [maaaaz/sqldeveloperpassworddecryptor#4]
How did you figure out what the salt was and that there were 42 iterations used?
Is there the source code available for sqldeveloper somewhere or did you de-compile it?
Awesome tool though helped me a lot.

**Comment by maaaaz** [comment]
Hello,

Thanks you for positive feedback.
As written in the readme, I just merged two snippets for the v3 and v4 versions.
I guess that the original authors found it through reverse-engineering the Java classes.

Cheers.

**Comment by mike5x3** [comment]
You will find the salt in the decompiled java class (ReferenceWorker.class for V23 in the jar file dbtools-common.jar).
