### ISSUE TITLE
Linux and Cygwin support.

### ISSUE THREAD

**Issue by deragon** [maaaaz/sqldeveloperpassworddecryptor#5]
To support Linux & Cygwin, simply change the fileformat to Linux (LF only, not CR/LF) and add the following as the first line of the script: `#!/usr/bin/env python`.  Save the *.py file as a Linux executable (chmod +x).

**Comment by maaaaz** [comment]
Thanks, fixed.

**Comment by deragon** [comment]
Works, except that `chmod +x` does not seamed to have been applied.  But I am using Cygwin under Windows so that might be the problem (permissions might not be properly copied over).  If you have Linux, please ensure that the executable bit is set on `sqldeveloperpassworddecryptor.py`.   Thank you.

**Comment by maaaaz** [comment]
Ah yes, it does not work as I use a shared folder between my host and my code pushing VM. That's not a big deal, people will `chmod +x`.
