### ISSUE TITLE
[patch] Python 3 support

### ISSUE THREAD

**Issue by VVD** [maaaaz/sqldeveloperpassworddecryptor#8]
I'm not a python developer, but this patch work for me on python 3.7:
[sqldeveloperpassworddecryptor.py.diff.txt](https://github.com/maaaaz/sqldeveloperpassworddecryptor/files/5460245/sqldeveloperpassworddecryptor.py.diff.txt)

**Comment by maaaaz** [comment]
Thanks, fixed in v2.0.
