### ISSUE TITLE
Returns nothing

### ISSUE THREAD

**Issue by RedAero** [maaaaz/sqldeveloperpassworddecryptor#9]
The program appears to run but simply returns what seems to be an empty string. I'm on SQL Dev 20, so there isn't a connections.xml anymore, it's json now.

**Comment by bollerdominik** [comment]
Same issue with SQL Dev 19.2

**Comment by maaaaz** [comment]
The cryptosystem [changed recently](https://community.oracle.com/tech/developers/discussion/4477010/where-are-connections-stored-in-19-4), I am pushing soon an update for `sqlpassworddecryptor`.

**Comment by maaaaz** [comment]
Fixed in v2.1

**Comment by bollerdominik** [comment]
Works perfect now. Thank you for your efforts!
